// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkzgmrQMMs4UL0cvdPN-g7zIU7H_Yi9wA',
    appId: '1:775055672102:web:7573878b6163a40fa277e7',
    messagingSenderId: '775055672102',
    projectId: 'social-media-flutter-4fefb',
    authDomain: 'social-media-flutter-4fefb.firebaseapp.com',
    storageBucket: 'social-media-flutter-4fefb.firebasestorage.app',
    measurementId: 'G-F9GD422DS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDc1-UJA-guhAmUEI9iJezRV6SMpWuAmg',
    appId: '1:775055672102:android:87a063a626225c86a277e7',
    messagingSenderId: '775055672102',
    projectId: 'social-media-flutter-4fefb',
    storageBucket: 'social-media-flutter-4fefb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxN2mC4-LN8mA1VXGu6PuVQp5TiIsaajM',
    appId: '1:775055672102:ios:eaee7090d025ef18a277e7',
    messagingSenderId: '775055672102',
    projectId: 'social-media-flutter-4fefb',
    storageBucket: 'social-media-flutter-4fefb.firebasestorage.app',
    iosBundleId: 'dev.alexandrakomkova.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxN2mC4-LN8mA1VXGu6PuVQp5TiIsaajM',
    appId: '1:775055672102:ios:eaee7090d025ef18a277e7',
    messagingSenderId: '775055672102',
    projectId: 'social-media-flutter-4fefb',
    storageBucket: 'social-media-flutter-4fefb.firebasestorage.app',
    iosBundleId: 'dev.alexandrakomkova.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkzgmrQMMs4UL0cvdPN-g7zIU7H_Yi9wA',
    appId: '1:775055672102:web:ad351b738f529bb0a277e7',
    messagingSenderId: '775055672102',
    projectId: 'social-media-flutter-4fefb',
    authDomain: 'social-media-flutter-4fefb.firebaseapp.com',
    storageBucket: 'social-media-flutter-4fefb.firebasestorage.app',
    measurementId: 'G-L2H02QW41D',
  );
}
